# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches: ["**"]
  pull_request:
    types:
      - closed # Lorsqu'on execute un merge request ou qu'on ferme une PR
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    name: build project and test
    runs-on: ubuntu-latest # L'environnement d'ex√©cution est Ubuntu

    steps:
      - uses: actions/checkout@v4 # Action pour installer composer

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
        continue-on-error: false

      - name: Run PHPUnit
        run: |
          APP_ENV=test XDEBUG_MODE=coverage  vendor/bin/phpunit
        continue-on-error: false

      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyse --level 9 --no-progress
        continue-on-error: false

      - name: Fail on error
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed. Blocking merge."
            exit 1
          fi
